name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 6 * * *'  # Runs at 12:00 PM IST (6:30 AM UTC)
  workflow_dispatch:

env:
  BASE_URL: https://example.com
  PORT: 8080

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn clean verify -DskipTests --file pom.xml
        env:
          BASE_URL: ${{ env.BASE_URL }}
          PORT: ${{ env.PORT }}

      - name: Cucumber Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: homework/target/cucumber/cucumber-reports.html

      - name: Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            homework/target/reports/cucumber-html-reports
